### ISSUE TITLE
🔨 [Chore] nestjs 개발 환경 설정

### ISSUE THREAD

**Issue by joosomi** [joosomi/aletheia#1]
## 🚀 Description
개발 시작을 위한 기본 nestjs 초기 환경 세팅

## ✅ TODO
- [x] Nestjs 기본 환경 설정 - 모노레포 설정
- [x] Maria DB 환경 세팅
- [x] 에러 및 특이사항 발생시 대처를 위한 로깅 설정

## 📢 Notes
인증서버 자원서버 디렉토리 따로
그리고 grpc 공부하기 
`env` 환경설정 파일 올리지 말고, `env.sample` 파일로 

자원, 인증 서버 Database 분리해서 docker compose로 maria DB 관리
