### ISSUE TITLE
✨ [Feature] 구매, 판매 주문 CRUD

### ISSUE THREAD

**Issue by joosomi** [joosomi/aletheia#7]
## 🚀 Description

 

- 구매, 판매 시 품목은 두 가지: 99.9% 금과 99.99% 금
- 수량 단위는 그램(g)이며, 최대 소수점 2번째 자리까지 처리 가능합니다. (request DTO 처리 시 유의)
- (소비자 입장에서의) 구매 주문은 "주문 완료", "입금 완료", "발송 완료" 상태를 가지며,
- (소비자 입장에서의) 판매 주문은 "주문 완료", "송금 완료", "수령 완료" 상태를 가집니다.
- 각 주문에 대하여 주문번호, 주문일자, 주문자, 상태, 품목, 수량, 금액, 배송지 정보를 저장합니다.(추가적인 정보도 저장 가능합니다)
- 주문번호는 자동으로 생성되며 Human Readable 해야합니다. => 딱 보고 바로 알 수 있게 
- 주문일자는 현재 시간으로 설정합니다.
- 주문의 상태 역시 특정 조건(API 호출)에 따라 바뀔 수 있어야 합니다.

_모든 response는 요청한 user의 권한에 맞는 invoice를 출력해야 합니다 => 권한에 맞게_ 
 #### Pagination을 활용하는 API 구현
- date, limit, offset, invoice type을 입력할 수 있으며, 다음과 같은 response를 제공해야 합니다:
```json
  {
    "success": true,
    "message": "Success to search invoices",
    "data": [
      {
        // 구매 또는 판매 주문 detail
      },
      // ...
    ],
    "links": {
      // pagination을 위한 추가적인 정보

    }
  }
```

## ✅ TODO
- [x] 서비스 로직 설계
  - [x] `GET /api/orders` : 주문 조회 및 Pagination 적용 
  - [x] `GET /api/orders/:orderId`: 금 주문 상세 조회
   - [x] `POST /api/orders/purchase` : 금 구매 주문 생성
  - [x] `POST /api/orders/sale` : 금 판매 주문 생성
  - [x] `PATCH /api/orders/:orderId/status` : 특정 주문 상태 변경
  - [x] `DELETE /api/orders/:orderId` : 주문 취소(soft delete)
- [x] 에러 처리
- [x] swagger

## 📢 Notes
DB 첨 시작할 때 품목 넣어주는게 없어서 임의로 넣어서 일단 개발 중..
DB_init 할 때 수정사항  아니면 따로 관리자용 API 도 추가 구현 요소
```
INSERT INTO product (id, type, purchasePricePerGram, salePricePerGram, createdAt, updatedAt) 
VALUES (UUID(), 'GOLD_999', 50.00, 55.00, NOW(), NOW());
```
일단 금이 2가지 품목이라 Enum 했지만 나중에는 그냥 purity 컬럼 추가하는게 낫지 않을까 싶다.
