### ISSUE TITLE
📝 [Docs] README 작성 및 문서화 작업

### ISSUE THREAD

**Issue by joosomi** [joosomi/aletheia#8]
## ✅ TODO

- [x] Quick Start 
   - [x] 서버 구동 가이드 작성 -> 제대로 확인
- [x] DB Diagram [dbdiagram.io](https://dbdiagram.io) 
- [x] API Swagger 문서화 ([Swagger](https://swagger.io) 링크를 포함)
- [ ] API 호출이 가능한 Postman  [Postman](https://www.postman.com) 링크 포함
- [x] dump file : 인증, 자원서버 2개의 DB 모두 .sql 파일

## 📢 Notes
Postman 링크 대신 간단한 테스트 코드로 API 요청 및 출력 확인 가능하도록 작성 가능.
-> 테코는 일단 다 구현하고 나서, 추후 우선순위
